# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dominion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dominion.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64ominion.proto\"\x84\x01\n\x04\x43\x61rd\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x03\x12\x18\n\x04type\x18\x03 \x03(\x0e\x32\n.Card.Type\x12\x0c\n\x04text\x18\x04 \x01(\t\"8\n\x04Type\x12\x0b\n\x07Victory\x10\x00\x12\x0c\n\x08Treasure\x10\x01\x12\n\n\x06\x41\x63tion\x10\x03\x12\t\n\x05\x43urse\x10\x04\"*\n\x04Pile\x12\x13\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x05.Card\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\" \n\x07Kingdom\x12\x15\n\x06supply\x18\x01 \x03(\x0b\x32\x05.Pile\"Y\n\x06Player\x12\x13\n\x04\x64\x65\x63k\x18\x01 \x03(\x0b\x32\x05.Card\x12\x13\n\x04hand\x18\x02 \x03(\x0b\x32\x05.Card\x12\x16\n\x07\x64iscard\x18\x03 \x03(\x0b\x32\x05.Card\x12\r\n\x05score\x18\x04 \x01(\x03\"\xf8\x01\n\x04Game\x12\x19\n\x07kingdom\x18\x01 \x01(\x0b\x32\x08.Kingdom\x12\x18\n\x07players\x18\x02 \x03(\x0b\x32\x07.Player\x12\x13\n\x04play\x18\x03 \x03(\x0b\x32\x05.Card\x12\x14\n\x05trash\x18\x04 \x03(\x0b\x32\x05.Card\x12\x0c\n\x04turn\x18\x05 \x01(\x03\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x03\x12\x1a\n\x05phase\x18\x07 \x01(\x0e\x32\x0b.Game.Phase\x12\x0f\n\x07\x61\x63tions\x18\x08 \x01(\x03\x12\x0c\n\x04\x63oin\x18\t \x01(\x03\x12\x0c\n\x04\x62uys\x18\n \x01(\x03\")\n\x05Phase\x12\n\n\x06\x41\x63tion\x10\x00\x12\x07\n\x03\x42uy\x10\x01\x12\x0b\n\x07\x43leanup\x10\x02\x62\x06proto3')
)



_CARD_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Card.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Victory', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Treasure', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Action', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Curse', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=95,
  serialized_end=151,
)
_sym_db.RegisterEnumDescriptor(_CARD_TYPE)

_GAME_PHASE = _descriptor.EnumDescriptor(
  name='Phase',
  full_name='Game.Phase',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Action', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Buy', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Cleanup', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=530,
  serialized_end=571,
)
_sym_db.RegisterEnumDescriptor(_GAME_PHASE)


_CARD = _descriptor.Descriptor(
  name='Card',
  full_name='Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Card.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='Card.cost', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Card.type', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='Card.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CARD_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=151,
)


_PILE = _descriptor.Descriptor(
  name='Pile',
  full_name='Pile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='card', full_name='Pile.card', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Pile.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=195,
)


_KINGDOM = _descriptor.Descriptor(
  name='Kingdom',
  full_name='Kingdom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supply', full_name='Kingdom.supply', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=229,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deck', full_name='Player.deck', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hand', full_name='Player.hand', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discard', full_name='Player.discard', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='Player.score', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=320,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kingdom', full_name='Game.kingdom', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='Game.players', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='play', full_name='Game.play', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trash', full_name='Game.trash', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turn', full_name='Game.turn', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active', full_name='Game.active', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase', full_name='Game.phase', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='Game.actions', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coin', full_name='Game.coin', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buys', full_name='Game.buys', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAME_PHASE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=571,
)

_CARD.fields_by_name['type'].enum_type = _CARD_TYPE
_CARD_TYPE.containing_type = _CARD
_PILE.fields_by_name['card'].message_type = _CARD
_KINGDOM.fields_by_name['supply'].message_type = _PILE
_PLAYER.fields_by_name['deck'].message_type = _CARD
_PLAYER.fields_by_name['hand'].message_type = _CARD
_PLAYER.fields_by_name['discard'].message_type = _CARD
_GAME.fields_by_name['kingdom'].message_type = _KINGDOM
_GAME.fields_by_name['players'].message_type = _PLAYER
_GAME.fields_by_name['play'].message_type = _CARD
_GAME.fields_by_name['trash'].message_type = _CARD
_GAME.fields_by_name['phase'].enum_type = _GAME_PHASE
_GAME_PHASE.containing_type = _GAME
DESCRIPTOR.message_types_by_name['Card'] = _CARD
DESCRIPTOR.message_types_by_name['Pile'] = _PILE
DESCRIPTOR.message_types_by_name['Kingdom'] = _KINGDOM
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Game'] = _GAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), dict(
  DESCRIPTOR = _CARD,
  __module__ = 'dominion_pb2'
  # @@protoc_insertion_point(class_scope:Card)
  ))
_sym_db.RegisterMessage(Card)

Pile = _reflection.GeneratedProtocolMessageType('Pile', (_message.Message,), dict(
  DESCRIPTOR = _PILE,
  __module__ = 'dominion_pb2'
  # @@protoc_insertion_point(class_scope:Pile)
  ))
_sym_db.RegisterMessage(Pile)

Kingdom = _reflection.GeneratedProtocolMessageType('Kingdom', (_message.Message,), dict(
  DESCRIPTOR = _KINGDOM,
  __module__ = 'dominion_pb2'
  # @@protoc_insertion_point(class_scope:Kingdom)
  ))
_sym_db.RegisterMessage(Kingdom)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'dominion_pb2'
  # @@protoc_insertion_point(class_scope:Player)
  ))
_sym_db.RegisterMessage(Player)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), dict(
  DESCRIPTOR = _GAME,
  __module__ = 'dominion_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  ))
_sym_db.RegisterMessage(Game)


# @@protoc_insertion_point(module_scope)
